const programs = {
  "Morning back stretching": [
    { secs: 10, caption: "Hamstring strech position"},
    { secs: 30, caption: "Right hamstring stretch" },
    { secs: 5, caption: "Switch legs" },
    { secs: 30, caption: "Left hamstring stretch" },
    { secs: 5, caption: "Switch legs" },
    { secs: 30, caption: "Right hamstring stretch" },
    { secs: 5, caption: "Switch legs" },
    { secs: 30, caption: "Left hamstring stretch" },
    { secs: 5, caption: "Switch legs" },
    { secs: 30, caption: "Right hamstring stretch" },
    { secs: 5, caption: "Switch legs" },
    { secs: 30, caption: "Left hamstring stretch" },
    { secs: 15, caption: "Pelvic tilt position" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 5, caption: "Knee to chest position" },
    { secs: 20, caption: "Right knee to chest" },
    { secs: 5, caption: "Switch legs" },
    { secs: 20, caption: "Left knee to chest" },
    { secs: 5, caption: "Switch legs" },
    { secs: 5, caption: "Bent leg pull position, left leg up"},
    { secs: 20, caption: "Pull" },
    { secs: 5, caption: "Switch legs, right leg up" },
    { secs: 20, caption: "Pull" },
    { secs: 5, caption: "Switch legs, left leg up" },
    { secs: 20, caption: "Pull" },
    { secs: 5, caption: "Switch legs, right leg up" },
    { secs: 20, caption: "Pull" },
    { secs: 5, caption: "Switch legs, left leg up" },
    { secs: 20, caption: "Pull" },
    { secs: 5, caption: "Switch legs, right leg up" },
    { secs: 20, caption: "Pull" },
    { secs: 5, caption: "Straight leg raise position"},
    { secs: 3, caption: "Lift" },
    { secs: 2, caption: "Down" },
    { secs: 3, caption: "Lift" },
    { secs: 2, caption: "Down" },
    { secs: 3, caption: "Lift" },
    { secs: 2, caption: "Down" },
    { secs: 3, caption: "Lift" },
    { secs: 2, caption: "Down" },
    { secs: 3, caption: "Lift" },
    { secs: 2, caption: "Down" },
    { secs: 3, caption: "Lift" },
    { secs: 2, caption: "Down" },
    { secs: 3, caption: "Lift" },
    { secs: 2, caption: "Down" },
    { secs: 3, caption: "Lift" },
    { secs: 2, caption: "Down" },
    { secs: 3, caption: "Lift" },
    { secs: 2, caption: "Down" },
    { secs: 3, caption: "Lift" },
    { secs: 5, caption: "Switch legs"},
    { secs: 3, caption: "Lift" },
    { secs: 2, caption: "Down" },
    { secs: 3, caption: "Lift" },
    { secs: 2, caption: "Down" },
    { secs: 3, caption: "Lift" },
    { secs: 2, caption: "Down" },
    { secs: 3, caption: "Lift" },
    { secs: 2, caption: "Down" },
    { secs: 3, caption: "Lift" },
    { secs: 2, caption: "Down" },
    { secs: 3, caption: "Lift" },
    { secs: 2, caption: "Down" },
    { secs: 3, caption: "Lift" },
    { secs: 2, caption: "Down" },
    { secs: 3, caption: "Lift" },
    { secs: 2, caption: "Down" },
    { secs: 3, caption: "Lift" },
    { secs: 2, caption: "Down" },
    { secs: 3, caption: "Lift" },
    { secs: 15, caption: "Cat/Camel position"},
    { secs: 12, caption: "Cat position" },
    { secs: 12, caption: "Camel position" },
    { secs: 12, caption: "Cat position" },
    { secs: 12, caption: "Camel position" },
    { secs: 12, caption: "Cat position" },
    { secs: 12, caption: "Camel position" },
    { secs: 12, caption: "Cat position" },
    { secs: 12, caption: "Camel position" },
    { secs: 12, caption: "Cat position" },
    { secs: 12, caption: "Camel position" },
    { secs: 0, caption: "Finished! Good job!"},
  ],
  "Evening back stretching": [
    { secs: 10, caption: "Hamstring strech position"},
    { secs: 30, caption: "Right hamstring stretch" },
    { secs: 5, caption: "Switch legs" },
    { secs: 30, caption: "Left hamstring stretch" },
    { secs: 5, caption: "Switch legs" },
    { secs: 30, caption: "Right hamstring stretch" },
    { secs: 5, caption: "Switch legs" },
    { secs: 30, caption: "Left hamstring stretch" },
    { secs: 5, caption: "Switch legs" },
    { secs: 30, caption: "Right hamstring stretch" },
    { secs: 5, caption: "Switch legs" },
    { secs: 30, caption: "Left hamstring stretch" },
    { secs: 15, caption: "Pelvic tilt position" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 5, caption: "Knee to chest position" },
    { secs: 20, caption: "Right knee to chest" },
    { secs: 5, caption: "Switch legs" },
    { secs: 20, caption: "Left knee to chest" },
    { secs: 5, caption: "Switch legs" },
    { secs: 5, caption: "Bent leg pull position, left leg up"},
    { secs: 20, caption: "Pull" },
    { secs: 5, caption: "Switch legs, right leg up" },
    { secs: 20, caption: "Pull" },
    { secs: 5, caption: "Switch legs, left leg up" },
    { secs: 20, caption: "Pull" },
    { secs: 5, caption: "Switch legs, right leg up" },
    { secs: 20, caption: "Pull" },
    { secs: 5, caption: "Switch legs, left leg up" },
    { secs: 20, caption: "Pull" },
    { secs: 5, caption: "Switch legs, right leg up" },
    { secs: 20, caption: "Pull" },
    { secs: 15, caption: "Curl up position" },
    { secs: 5, caption: "Curl up" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Curl up" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Curl up" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Curl up" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Curl up" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Curl up" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Curl up" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Curl up" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Curl up" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Curl up" },
    { secs: 15, caption: "Combination position" },
    { secs: 4, caption: "Left" },
    { secs: 2, caption: "Down" },
    { secs: 4, caption: "Right" },
    { secs: 2, caption: "Down" },
    { secs: 4, caption: "Left" },
    { secs: 2, caption: "Down" },
    { secs: 4, caption: "Right" },
    { secs: 2, caption: "Down" },
    { secs: 4, caption: "Left" },
    { secs: 2, caption: "Down" },
    { secs: 4, caption: "Right" },
    { secs: 2, caption: "Down" },
    { secs: 4, caption: "Left" },
    { secs: 2, caption: "Down" },
    { secs: 4, caption: "Right" },
    { secs: 2, caption: "Down" },
    { secs: 4, caption: "Left" },
    { secs: 2, caption: "Down" },
    { secs: 4, caption: "Right" },
    { secs: 2, caption: "Down" },
    { secs: 4, caption: "Left" },
    { secs: 2, caption: "Down" },
    { secs: 4, caption: "Right" },
    { secs: 2, caption: "Down" },
    { secs: 4, caption: "Left" },
    { secs: 2, caption: "Down" },
    { secs: 4, caption: "Right" },
    { secs: 2, caption: "Down" },
    { secs: 4, caption: "Left" },
    { secs: 2, caption: "Down" },
    { secs: 4, caption: "Right" },
    { secs: 2, caption: "Down" },
    { secs: 4, caption: "Left" },
    { secs: 2, caption: "Down" },
    { secs: 4, caption: "Right" },
    { secs: 2, caption: "Down" },
    { secs: 4, caption: "Left" },
    { secs: 2, caption: "Down" },
    { secs: 4, caption: "Right" },
    { secs: 2, caption: "Down" },
    { secs: 15, caption: "Cat/Camel position"},
    { secs: 12, caption: "Cat position" },
    { secs: 12, caption: "Camel position" },
    { secs: 12, caption: "Cat position" },
    { secs: 12, caption: "Camel position" },
    { secs: 12, caption: "Cat position" },
    { secs: 12, caption: "Camel position" },
    { secs: 12, caption: "Cat position" },
    { secs: 12, caption: "Camel position" },
    { secs: 12, caption: "Cat position" },
    { secs: 12, caption: "Camel position" },
    { secs: 0, caption: "Finished! Good job!" },
  ],
  "Level I, Workout 1": [
    { secs: 10, caption: "Opposite arm leg reach position, set one" },
    { secs: 2, caption: "Left" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Right" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Left" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Right" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Left" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Right" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Left" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Right" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Left" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Right" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Left" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Right" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Left" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Right" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Left" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Right" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Left" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Right" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Left" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Right" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 25, caption: "Rest" },
    { secs: 5, caption: "Set two" },
    { secs: 2, caption: "Left" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Right" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Left" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Right" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Left" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Right" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Left" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Right" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Left" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Right" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Left" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Right" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Left" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Right" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Left" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Right" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Left" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Right" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Left" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 2, caption: "Right" },
    { secs: 5, caption: "Hold" },
    { secs: 2, caption: "Down" },
    { secs: 15, caption: "Hip Bridge with Heel Slides, set one" },
    { secs: 2, caption: "Left" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Right" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Left" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Right" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Left" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Right" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Left" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Right" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Left" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Right" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Left" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Right" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Left" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Right" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Left" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Right" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Left" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Right" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Left" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Right" },
    { secs: 3, caption: "Back" },
    { secs: 25, caption: "Rest" },
    { secs: 5, caption: "Set two" },
    { secs: 2, caption: "Left" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Right" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Left" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Right" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Left" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Right" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Left" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Right" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Left" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Right" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Left" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Right" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Left" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Right" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Left" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Right" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Left" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Right" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Left" },
    { secs: 3, caption: "Back" },
    { secs: 2, caption: "Right" },
    { secs: 3, caption: "Back" },
    { secs: 15, caption: "Rest" },
    { secs: 15, caption: "TVA Activation" },
    { secs: 5, caption: "Hold" },
    { secs: 5, caption: "Rest" },
    { secs: 5, caption: "Hold" },
    { secs: 5, caption: "Rest" },
    { secs: 5, caption: "Hold" },
    { secs: 5, caption: "Rest" },
    { secs: 5, caption: "Hold" },
    { secs: 5, caption: "Rest" },
    { secs: 5, caption: "Hold" },
    { secs: 15, caption: "Tailbone Tucks" },
    { secs: 5, caption: "Hold" },
    { secs: 5, caption: "Rest" },
    { secs: 5, caption: "Hold" },
    { secs: 5, caption: "Rest" },
    { secs: 5, caption: "Hold" },
    { secs: 5, caption: "Rest" },
    { secs: 5, caption: "Hold" },
    { secs: 5, caption: "Rest" },
    { secs: 5, caption: "Hold" },
    { secs: 0, caption: "Finished! Good job!" },
  ]
};

export default programs;
