export const eveningSegments = [
  { secs: 30, caption: "Right hamstring stretch" },
  { secs: 5, caption: "Switch legs" },
  { secs: 30, caption: "Left hamstring stretch" },
  { secs: 5, caption: "Switch legs" },
  { secs: 30, caption: "Right hamstring stretch" },
  { secs: 5, caption: "Switch legs" },
  { secs: 30, caption: "Left hamstring stretch" },
  { secs: 5, caption: "Switch legs" },
  { secs: 30, caption: "Right hamstring stretch" },
  { secs: 5, caption: "Switch legs" },
  { secs: 30, caption: "Left hamstring stretch" },
  { secs: 15, caption: "Pelvic tilt position" },
  { secs: 5, caption: "Pelvic tilt" },
  { secs: 3, caption: "Rest" },
  { secs: 5, caption: "Pelvic tilt" },
  { secs: 3, caption: "Rest" },
  { secs: 5, caption: "Pelvic tilt" },
  { secs: 3, caption: "Rest" },
  { secs: 5, caption: "Pelvic tilt" },
  { secs: 3, caption: "Rest" },
  { secs: 5, caption: "Pelvic tilt" },
  { secs: 3, caption: "Rest" },
  { secs: 5, caption: "Pelvic tilt" },
  { secs: 3, caption: "Rest" },
  { secs: 5, caption: "Pelvic tilt" },
  { secs: 3, caption: "Rest" },
  { secs: 5, caption: "Pelvic tilt" },
  { secs: 3, caption: "Rest" },
  { secs: 5, caption: "Pelvic tilt" },
  { secs: 3, caption: "Rest" },
  { secs: 5, caption: "Pelvic tilt" },
  { secs: 15, caption: "Curl up position" },
  { secs: 5, caption: "Curl up" },
  { secs: 3, caption: "Rest" },
  { secs: 5, caption: "Curl up" },
  { secs: 3, caption: "Rest" },
  { secs: 5, caption: "Curl up" },
  { secs: 3, caption: "Rest" },
  { secs: 5, caption: "Curl up" },
  { secs: 3, caption: "Rest" },
  { secs: 5, caption: "Curl up" },
  { secs: 3, caption: "Rest" },
  { secs: 5, caption: "Curl up" },
  { secs: 3, caption: "Rest" },
  { secs: 5, caption: "Curl up" },
  { secs: 3, caption: "Rest" },
  { secs: 5, caption: "Curl up" },
  { secs: 3, caption: "Rest" },
  { secs: 5, caption: "Curl up" },
  { secs: 3, caption: "Rest" },
  { secs: 5, caption: "Curl up" },
  { secs: 15, caption: "Cat/Camel position"},
  { secs: 12, caption: "Cat position" },
  { secs: 12, caption: "Camel position" },
  { secs: 12, caption: "Cat position" },
  { secs: 12, caption: "Camel position" },
  { secs: 12, caption: "Cat position" },
  { secs: 12, caption: "Camel position" },
  { secs: 12, caption: "Cat position" },
  { secs: 12, caption: "Camel position" },
  { secs: 12, caption: "Cat position" },
  { secs: 12, caption: "Camel position" },
  { secs: 0, caption: "Finished! Good job!" },
];

export const morningSegments = [
  { secs: 30, caption: "Right hamstring stretch" },
  { secs: 5, caption: "Switch legs" },
  { secs: 30, caption: "Left hamstring stretch" },
  { secs: 5, caption: "Switch legs" },
  { secs: 30, caption: "Right hamstring stretch" },
  { secs: 5, caption: "Switch legs" },
  { secs: 30, caption: "Left hamstring stretch" },
  { secs: 5, caption: "Switch legs" },
  { secs: 30, caption: "Right hamstring stretch" },
  { secs: 5, caption: "Switch legs" },
  { secs: 30, caption: "Left hamstring stretch" },
  { secs: 15, caption: "Pelvic tilt position" },
  { secs: 5, caption: "Pelvic tilt" },
  { secs: 3, caption: "Rest" },
  { secs: 5, caption: "Pelvic tilt" },
  { secs: 3, caption: "Rest" },
  { secs: 5, caption: "Pelvic tilt" },
  { secs: 3, caption: "Rest" },
  { secs: 5, caption: "Pelvic tilt" },
  { secs: 3, caption: "Rest" },
  { secs: 5, caption: "Pelvic tilt" },
  { secs: 3, caption: "Rest" },
  { secs: 5, caption: "Pelvic tilt" },
  { secs: 3, caption: "Rest" },
  { secs: 5, caption: "Pelvic tilt" },
  { secs: 3, caption: "Rest" },
  { secs: 5, caption: "Pelvic tilt" },
  { secs: 3, caption: "Rest" },
  { secs: 5, caption: "Pelvic tilt" },
  { secs: 3, caption: "Rest" },
  { secs: 5, caption: "Pelvic tilt" },
  { secs: 15, caption: "Cat/Camel position"},
  { secs: 12, caption: "Cat position" },
  { secs: 12, caption: "Camel position" },
  { secs: 12, caption: "Cat position" },
  { secs: 12, caption: "Camel position" },
  { secs: 12, caption: "Cat position" },
  { secs: 12, caption: "Camel position" },
  { secs: 12, caption: "Cat position" },
  { secs: 12, caption: "Camel position" },
  { secs: 12, caption: "Cat position" },
  { secs: 12, caption: "Camel position" },
  { secs: 0, caption: "Finished! Good job!"},
];

export const testSegments = [
  { secs: 2, caption: "This is just a test" },
  { secs: 0, caption: "Finished! Good job!" },
]
