const segments = {
  "Morning back stretching": [
    { secs: 10, caption: "Hamstring strech position"},
    { secs: 30, caption: "Right hamstring stretch" },
    { secs: 5, caption: "Switch legs" },
    { secs: 30, caption: "Left hamstring stretch" },
    { secs: 5, caption: "Switch legs" },
    { secs: 30, caption: "Right hamstring stretch" },
    { secs: 5, caption: "Switch legs" },
    { secs: 30, caption: "Left hamstring stretch" },
    { secs: 5, caption: "Switch legs" },
    { secs: 30, caption: "Right hamstring stretch" },
    { secs: 5, caption: "Switch legs" },
    { secs: 30, caption: "Left hamstring stretch" },
    { secs: 15, caption: "Pelvic tilt position" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 5, caption: "Knee to chest position" },
    { secs: 20, caption: "Right knee to chest" },
    { secs: 5, caption: "Switch legs" },
    { secs: 20, caption: "Left knee to chest" },
    { secs: 5, caption: "Switch legs" },
    { secs: 20, caption: "Right knee to chest" },
    { secs: 5, caption: "Switch legs" },
    { secs: 20, caption: "Left knee to chest" },
    { secs: 5, caption: "Switch legs" },
    { secs: 20, caption: "Right knee to chest" },
    { secs: 5, caption: "Switch legs" },
    { secs: 20, caption: "Left knee to chest" },
    { secs: 15, caption: "Cat/Camel position"},
    { secs: 12, caption: "Cat position" },
    { secs: 12, caption: "Camel position" },
    { secs: 12, caption: "Cat position" },
    { secs: 12, caption: "Camel position" },
    { secs: 12, caption: "Cat position" },
    { secs: 12, caption: "Camel position" },
    { secs: 12, caption: "Cat position" },
    { secs: 12, caption: "Camel position" },
    { secs: 12, caption: "Cat position" },
    { secs: 12, caption: "Camel position" },
    { secs: 0, caption: "Finished! Good job!"},
  ],
  "Evening back stretching": [
    { secs: 10, caption: "Hamstring strech position"},
    { secs: 30, caption: "Right hamstring stretch" },
    { secs: 5, caption: "Switch legs" },
    { secs: 30, caption: "Left hamstring stretch" },
    { secs: 5, caption: "Switch legs" },
    { secs: 30, caption: "Right hamstring stretch" },
    { secs: 5, caption: "Switch legs" },
    { secs: 30, caption: "Left hamstring stretch" },
    { secs: 5, caption: "Switch legs" },
    { secs: 30, caption: "Right hamstring stretch" },
    { secs: 5, caption: "Switch legs" },
    { secs: 30, caption: "Left hamstring stretch" },
    { secs: 15, caption: "Pelvic tilt position" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Pelvic tilt" },
    { secs: 5, caption: "Knee to chest position" },
    { secs: 20, caption: "Right knee to chest" },
    { secs: 5, caption: "Switch legs" },
    { secs: 20, caption: "Left knee to chest" },
    { secs: 5, caption: "Switch legs" },
    { secs: 20, caption: "Right knee to chest" },
    { secs: 5, caption: "Switch legs" },
    { secs: 20, caption: "Left knee to chest" },
    { secs: 5, caption: "Switch legs" },
    { secs: 20, caption: "Right knee to chest" },
    { secs: 5, caption: "Switch legs" },
    { secs: 20, caption: "Left knee to chest" },
    { secs: 15, caption: "Curl up position" },
    { secs: 5, caption: "Curl up" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Curl up" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Curl up" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Curl up" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Curl up" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Curl up" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Curl up" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Curl up" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Curl up" },
    { secs: 3, caption: "Rest" },
    { secs: 5, caption: "Curl up" },
    { secs: 15, caption: "Cat/Camel position"},
    { secs: 12, caption: "Cat position" },
    { secs: 12, caption: "Camel position" },
    { secs: 12, caption: "Cat position" },
    { secs: 12, caption: "Camel position" },
    { secs: 12, caption: "Cat position" },
    { secs: 12, caption: "Camel position" },
    { secs: 12, caption: "Cat position" },
    { secs: 12, caption: "Camel position" },
    { secs: 12, caption: "Cat position" },
    { secs: 12, caption: "Camel position" },
    { secs: 0, caption: "Finished! Good job!" },
  ],
};

export default segments;
